### PR TITLE
feat: add syntax highlighting

### PR DESCRIPTION
**Pull request by kadaliao**

### CODE REVIEW

**Comment by kadaliao** [comment]
change pyyaml version to 3.1.3 to avoid this error: https://github.com/yaml/pyyaml/issues/152

**Comment by benwr** [comment]
I think you need to add a value for `highlight` to the default CONFIG; otherwise this looks great!

**Comment by benwr** [comment]
Ah, actually I think you need to add dependencies to `setup.py` as well

**Comment by kadaliao** [comment]
@benwr done.

**Pull request merged**
